### ISSUE TITLE
(VC) Add key bindings

### ISSUE THREAD

**Issue by csparker247** [educelab/volume-cartographer#14]
From Hari_Seldon:

> LR arrows for previous/next (shift modifier for x10)
+,- for zoom in/out (no ctrl)
[,] for decrease/increase impact range
remap alt to ctrl for scrolling X axis
a/d for previous/next (shift modifier for jumping by 10)
w/s for zoom in/out
q/e for decrease/increase impact range
ctrl + mouse for X-axis panning

**Comment by hariseldon137** [comment]
Now that the segmentation team is growing, improvements here will compound. 

Getting impact range off the slider and onto the keyboard is by far the most important fix here. Second most important is zoom. 

But if the only thing we can do is impact range, that alone is a game changer. Thanks!!!
