### ISSUE TITLE
(VC) alt + mousewheel not working on the segmenter's server

### ISSUE THREAD

**Issue by hariseldon137** [educelab/volume-cartographer#29]

**Comment by csparker247** [comment]
Can you provide more description of the problem? What do you expect it to do? I don't know what the "segmenters server" is. Are you saying it works on some platform but not another? What are the differences between these two? Is one running Docker?

Alt + Mouse Wheel is also not explicitly coded into the application, so it sounds like you're dealing with default Qt behavior.

**Comment by hariseldon137** [comment]
There is a Ubuntu server up and running that all the segmenters (except myself) are working on, using the NoMachine client to run multiple sessions. 

In VC to pan around the image, the mouse wheel pans up/down, and mouse wheel + alt pans left/right. For some reason this is not the case on the server - mouse wheel + alt only reverses the vertical panning. 

This is a critical issue, it alone might be more than doubling the time to unroll the scroll.

**Comment by csparker247** [comment]
This is an issue with NoMachine, not VC: https://forum.nomachine.com/topic/artifacts-on-dual-monitors-and-scrolling-issue
