### ISSUE TITLE
Need to install libtiff manually

### ISSUE THREAD

**Issue by tomhsiao1260** [educelab/volume-cartographer#5]
I've followed [tutorial3](https://scrollprize.org/tutorial3) in Vesuvius Challenge and installed Volume Cartographer with the following command on Mac

`brew install --no-quarantine educelab/casks/volume-cartographer`

This command run successfully and I can see Volume Cartographer appear in my application folder. However, when I try to run

`vc_render --help`

The following error occur:
```
dyld[4064]: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
Referenced from: <9298E93C-EB87-3AFD-9366-F05D82C15B87> /usr/local/Caskroom/volume-cartographer/2.24.0/bin/vc_render
Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)
[1]    4064 abort   vc_render --help
```

Seems I need to install libtiff to run this app, so I install it manually and after that `vc_render --help` command works now.

`brew install libtiff`

Not sure if it's an issue. If not or I'm doing something wrong, please let me know and I will close it later, thanks!

**Comment by csparker247** [comment]
Thanks for reporting this. This is probably an issue with our package build environment. Are you running on an Intel or Arm Mac?

**Comment by csparker247** [comment]
Oh, I see in #6 that you're on Intel. The GH runners we build the Intel packages with come preinstalled with homebrew and various packages, so that's probably what's causing the issue. I'll see if I can get it fixed soon.

**Comment by tomhsiao1260** [comment]
Good to know this, thanks.

**Comment by csparker247** [comment]
Yeah, I've confirmed that it's just picking up the Homebrew libtiff instead of our statically built one. There probably won't be a fixed package for this until early next week. In the meantime, Intel users can `brew install libtiff` as you did as a workaround.

Thanks!
