### ISSUE TITLE
[Bug] Tutorial 3 is pointing to a different vc_packager build in its docker image

### ISSUE THREAD

**Issue by kristopolous** [educelab/volume-cartographer#83]
### What happened?

So I'm looking at `apps/src/Packager.cpp` in the \.add_options() segments and I see the options described [in tutorial 3](https://scrollprize.org/tutorial3) at this line

```
vc_packager -v campfire.volpkg -m 1000 -n campfire -u 26.3 -s ~/campfire/rec/ # Or /campfire/rec when using Docker
```

However when you run the line above:

```
docker run -it -v C:\campfire:/campfire --env="DISPLAY=host.docker.internal:0" ghcr.io/educelab/volume-cartographer
```
and do a `vc_packager --help`  you clearly get a reduced set of options, probably from an earlier build.

If you go through the cmake instruction in the README.md (which is of course a bigger lift), the options do show up.

On the left side is the build from 0e9c34995155a48030d0dc859be0c3a3fa6e4949 and on the right side is the docker.

vc_version output for the two are

2.26.0 and 2.25.0 respectively.
![compare](https://github.com/educelab/volume-cartographer/assets/231761/92d932bf-73fa-405b-a9ba-74d68a6c9ca5)

### Steps to reproduce

Follow https://scrollprize.org/tutorial3 to the letter.

### Version

2.25.0

### How did you install the software?

Docker

### On which operating systems have you experienced this issue?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csparker247** [comment]
Yes, these command line options [changed in the last few months](https://github.com/educelab/volume-cartographer/pull/62) and are likely to [change again soon](https://github.com/educelab/volume-cartographer/pull/82). 

`ghcr.io/educelab/volume-cartographer` always pulls the `latest` tag, which always points at the latest release. As v2.26 is still a release candidate, `latest` continues to point at v2.25 (see the tags [here](https://github.com/educelab/volume-cartographer/pkgs/container/volume-cartographer)). If you want to follow the tutorial with v2.26, then modify your Docker command to pull that version:
```shell
docker run ... ghcr.io/educelab/volume-cartographer:v2.26.0-rc3 # or edge
```

When v2.26 is released properly (hopefully within the next month), the Scroll Prize tutorial will need to be updated accordingly (@stephenrparsons).
